apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-example
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dinesh
  strategy:
    type: Recreate
    #type: RollingUpdate
    #rollingUpdate:
     # maxSurge: 1
      #maxUnavailable: 0
  template:
    metadata:
      labels:
        app: dinesh
    spec:
      containers:
      - name: nginx
        image: jilu407/hari-app
        ports:
        - containerPort: 80