apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: d-hostpath
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /usr/share/nginx/html/