apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-statefulset
  serviceName: my-service
  template:
    metadata:
      labels:
        app: my-statefulset
    spec:
      containers:
      - name: my-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: my-volume
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: my-volume
        configMap:
          name: my-configmap # Change to your ConfigMap or Secret name   
  volumeClaimTemplates:
  - metadata:
      name: my-volume-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  


---
apiVersion: v1
kind: Service
metadata:
  name: my-statefulset-service
spec:
  selector:
    app:  my-statefulset
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30033
  type: NodePort
